title:Chenke Qiu's Homepage
page-top-title: Chenke Qiu
top-section-bg-text: Intelligent Computation
home-subtitle: Chenke Qiu&ensp;|&ensp;邱陈柯
copyright-text: '&copy; Chenke Qiu 2025-2026. All Rights Reserved.'
